# BoostEconomy made by ItsWagPvP for BoostDevTeam
# Ver 1.2.4
# -
# The updater didn't works under 1.12 !! (If you enable the plugin function don't change)
# Note that this sounds work only from 1.9+
# If you want you can change this or disable
# -
# ConsoleSaveMessage: When a player join the console send the message of saving data
# StartMoney: Default money on join for the first time
# PlayerCheckForUpdates: Need to have the "boosteconomy.checkforupdates" permission
# UseSounds: You can disable this if you don't want to hear sounds of the commands
# -
# For the entity kill rewards watch the bottom of this file
# and then go and look mobs.yml file to disable some entities

Messages:
  General:
    NoPerms: "&b&lBoostEconomy &8--> &cYou do not have enough permissions"
    NoConsole: "&b&lBoostEconomy &8--> &cYou can't do this from console"
    NoPlayer: "&b&lBoostEconomy &8--> &cYou can't do this from player!"
    Reload: "&b&lBoostEconomy &8--> &aThe plugin has been reloaded with success!"
    InvalidArgs: "&b&lBoostEconomy &8--> &7Invalid args! /be <reload/help/checkforupdates/depug>"
  Money:
    Chat: "&b&lMoney &8--> &7You have &a%money%$"
    Done: "&b&lMoney &8--> &aDone!"
    Refreshed: "&b&lMoney &8--> &7Your money has been changed, now you have &a%money%$"
    Pay:
      Send: "&b&lMoney &8--> &7You have sent &c%money%$ &7to &c%target%"
      Received: "&b&lMoney &8--> &7You have received &c%money%$ &7from &c%player%"
    InvalidArgs:
      Pay: "&b&lMoney &8--> &7Invalid args! /pay <player> <money>"
      Eco: "&b&lMoney &8--> &7Invalid args! /eco <player> <set/take/give> <money>"
      Reset: "&b&lMoney &8--> &7Invalid args! /ecoreset <player>"
    PlayerNotFound: "&b&lMoney &8--> &cPlayer not found!"
    NoMoney: "&b&lMoney &8--> &cYou do not have enough money!"
    Others: "&b&lMoney &8--> &a%target% &7has &a%money%$"
    PayYourself: "&b&lMoney &8--> &cYou can't pay yourself!"
    Resetted: "&b&lMoney &8--> &7Your money has been restored to &c%money%$"
  BalTop:
    Header: "&c&lTop 10 balances"
    PlayerFormat: "&6%number%) &f&l%player%: &c%money%$"

Config:
  AdvancedDebug: false
  Placeholders: true
  CheckForUpdates:
    Console: true
    Player: true
  StartMoney: 0.00
  ConsoleSaveMessage: true
  UseSounds: true
  Sounds:
    Success: "ENTITY_PLAYER_LEVELUP"
    Error: "ENTITY_VILLAGER_NO"

GUI:
  Money:
    UseGUI: false
    Title: "&9&lMoney"
    YourHead: "&cYou have %money%$"
    OthersHead: "&c%target% has %money%$"
  BalTop:
    UseGUI: false
    Title: "&9&lTop 10 balances"
    Number: "&b&l%number%°"
    Lore: "&f&l%player%: &c%money%"

Banknotes:
  UseBanknotes: true
  Material: PAPER
  Data: 0
  Name: "&9Banknotes"
  Maximun-Float-Amount: 2
  Minimum-Float-Amount: 0
  Maximum-Withdraw-Amount: 100000000
  Minimun-Withdraw-Amount: 0
  Console-Name: "Console"
  Lore:
    - "&7Value: &a$%money%"
    - "&7Withdrawn by &a%player%"
  Allow-Right-Click-To-Deposit-Notes: true
  Messages:
    Note-Redeemed: "&b&lBanknote &8--> &7Banknote for &a%money%$ &7has been redeemed"
    Invalid-Number: "&b&lBanknote &8--> &cThe number that you have inserted is invalid!"
    Less-Than-Minimum: "&b&lBanknote &8--> &cThe number that you have inserted is lower than the minimum!"
    More-than-Maximum: "&b&lBanknote &8--> &cThe number that you have inserted is bigger than the maximum!"
    Insufficient-Funds: "&b&lBanknote &8--> &eYou don't have enough money!"
    Inventory-Full: "&b&lBanknote &8--> &cYour inventory is full!"
    Note-Created: "&b&lBanknote &8--> &7You have successfully created a banknotes of &a%money%$!"
    Player-Not-Found: "&b&lBanknote &8--> &cPlayer not found!"
    Note-Received: "&b&lBanknote &8--> &7You have received a banknote of &a%money%$&7 by &c%player%"
    Note-Given: "&b&lBanknote &8--> &7You have given a banknotes of &c%money%$&7 to &a%player%"
    Invalid-Note: "&b&lBanknote &8--> &cThe banknote is invalid"
    Nothing-In-Hand: "&b&lBanknote &8--> &cYou don't have nothing in your hand!"

# For more options go in the mobs.yml file
Entity:
  Enable: true
  SendMessage: true
  KillMessage: "&b&lKill &8--> &7You have killed &c%mob% &7and you have earned &a%money%$"