# BoostEconomy made by ItsWagPvP for BoostDevTeam
# Ver 1.1.2
# -
# Local placeholders:
# %money% = The player's money
# %target% = Target player name
# %player% = The player who have done the action
# -
# The GUI.UseGUI can only use in 1.14+ (If true the plugin reset the GUI.UseGUI option)
# The updater didn't works under 1.12 !! (If you enable the plugin function don't change)
# -
# ConsoleSaveMessage: When a player join the console send the message of saving data
# StartMoney: Default money on join for the first time
# PlayerCheckForUpdates: Need to have the "boosteconomy.checkforupdates" permission

Messages:
  General:
    NoPerms: "&b&lBoostEconomy &8--> &cYou do not have enough permissions"
    NoConsole: "&b&lBoostEconomy &8--> &cYou can't do this from console"
    NoPlayer: "&b&lBoostEconomy &8--> &cYou can't do this from player!"
    Reload: "&b&lBoostEconomy &8--> &aThe plugin has been reloaded with success!"
    InvalidArgs: "&b&lBoostEconomy &8--> &7Invalid args! /be <reload/help>"
  Money:
    Chat: "&b&lMoney &8--> &7You have &a%money%$"
    Done: "&b&lMoney &8--> &aDone!"
    Refreshed: "&b&lMoney &8--> &7Your money has been changed, now you have &a%money%$"
    Pay:
      Send: "&b&lMoney &8--> &7You have sent &c%money%$ &7to &c%target%"
      Received: "&b&lMoney &8--> &7You have received &c%money%$ &7from &c%player%"
    InvalidArgs:
      Pay: "&b&lMoney &8--> &7Invalid args! /pay <player> <money>"
      Eco: "&b&lMoney &8--> &7Invalid args! /eco <player> <set/take/give> <money>"
      Reset: "&b&lMoney &8--> &7Invalid args! /ecoreset <player>"
    PlayerNotFound: "&b&lMoney &8--> &cPlayer not found!"
    NoMoney: "&b&lMoney &8--> &cYou do not have enough money!"
    Others: "&b&lMoney &8--> &a%target% &7has &a%money%$"
    PayYourself: "&b&lMoney &8--> &cYou can't pay yourself!"
    Resetted: "&b&lMoney &8--> &7Your money has been resetted to &c%money%$"

Config:
  CheckForUpdates:
    Console: true
    Player: true
  StartMoney: 0.00
  ConsoleSaveMessage: true
GUI:
  UseGUI: false
  InvalidVersion: "&b&lBoostEconomy &8--> &cYou can't use GUI in this version"
  Money:
    Title: "&9&lMoney"
    YourHead: "&cYou have %money%$"
    OthersHead: "&c%target% has %money%$"
