name: BoostEconomy
version: 1.2.1
api-version: 1.13
main: boostdevteam.boosteconomy.BoostEconomy
load: POSTWORLD
author: _ItsWagPvP
description: An economy plugin based with Vault
website: www.boostdevteam.eu
softdepend:
  - PlaceholderAPI
commands:
  money:
    description: Show your's money
    aliases:
      - bal
      - balance
  eco:
    description: Admin command
    aliases:
      - economy
  pay:
    description: Send money to a player
  be:
    description: Main command
    aliases:
      - boosteconomy
      - boosteco
  ecoreset:
    description: Resets the money of a player
    aliases:
      - moneyreset
      - economyreset
      - boosteconomyreset
      - boosteconomyresetmoney
  baltop:
    description:
    aliases:
      - balancetop
  banknotes:
    description: Central command of the banknotes
  withdraw:
    description: Create a banknotes
  deposit:
    description: If you have a banknote in your hand it will be taken