name: BoostEconomy
version: 1.1.3
api-version: 1.13
main: boostdevteam.boosteconomy.BoostEconomy
load: STARTUP
author: _ItsWagPvP
description: An economy plugin based with Vault
website: www.boostdevteam.eu
commands:
  money:
    description: Show your's money
    aliases:
      - bal
      - balance
  eco:
    description: Admin command
    aliases:
      - economy
  pay:
    description: Send money to a player
  be:
    description: Main command
    aliases:
      - boosteconomy
      - boosteco
  ecoreset:
    description: Resets the money of a player
    aliases:
      - moneyreset
      - economyreset
      - boosteconomyreset
      - oosteconomyresetmoney
  baltop:
    description:
    aliases:
      - balancetop